### ISSUE TITLE
Caffe module doesn't exist

### ISSUE THREAD

**Issue by ghost** [jayelm/neural-art#3]
Caffe doesn't exist on Pip. So I installed Caffe2, but it also couldn't find it after install. Not sure how to fix the issue as I haven't seen a module folder looking like this before.

**Comment by jayelm** [comment]
Hi,

This codebase is very old at this point, Caffe hasn't been updated in a long time, and nowadays there exist several many cleaner implementations of neural style transfer algorithms in more recent frameworks where you'll also get quicker support - e.g. I'd recommend checking out

https://github.com/pytorch/examples/tree/master/fast_neural_style
